jobs:
  - script: >
      freeStyleJob('seed-job') {
        triggers {
          hudsonStartupTrigger {
            quietPeriod("2")
            runOnChoice("ON_CONNECT")
            label("")
            nodeParameterName("")
          }
        }
          scm {
            git {
              remote {
                url('https://github.com/daniyalAhmed-code/Jenkins-JobDSL.git')
                credentials('githiub-token')
              }
              branches('main')
            }
          }
        
        displayName('seed-job')
        steps {
          dsl {
            external('jobs/build/*.groovy', 'jobs/build/*.groovy')
          }
        }
        
      }